Error: 16.08.2020 20:36:41 
 System.ArgumentException: The key value at position 0 of the call to 'DbSet<ApplicationUser>.Find' was of type 'int', which does not match the property type of 'long'.
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindTracked(Object[] keyValues, IReadOnlyList`1& keyProperties)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Find(Object[] keyValues)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Find(Object[] keyValues)
   at Store.DataAccess.Repositories.EFRepositories.UserRepository.GetUserById(Int32 userId) in C:\Users\Gennadii\Desktop\Anuitex\StoreApp\Store.DataAccess\Repositories\EFRepositories\UserRepository.cs:line 26
   at Store.BusinessLogic.Services.UserService.GetUserById(Int32 userId) in C:\Users\Gennadii\Desktop\Anuitex\StoreApp\Store.BusinessLogic\Services\UserService.cs:line 24
   at Store.Presentation.Controllers.UserController.GetUserById(Int32 userId) in C:\Users\Gennadii\Desktop\Anuitex\StoreApp\Store.Presentation\Controllers\UserController.cs:line 29
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Store.Presentation.Middlewares.ErrorHandlerMiddleware.InvokeAsync(HttpContext context) in C:\Users\Gennadii\Desktop\Anuitex\StoreApp\Store.Presentation\Middlewares\ErrorHandlerMiddleware.cs:line 22
Error: 16.08.2020 20:36:57 
 System.ArgumentException: The key value at position 0 of the call to 'DbSet<ApplicationUser>.Find' was of type 'int', which does not match the property type of 'long'.
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindTracked(Object[] keyValues, IReadOnlyList`1& keyProperties)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Find(Object[] keyValues)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Find(Object[] keyValues)
   at Store.DataAccess.Repositories.EFRepositories.UserRepository.GetUserById(Int32 userId) in C:\Users\Gennadii\Desktop\Anuitex\StoreApp\Store.DataAccess\Repositories\EFRepositories\UserRepository.cs:line 26
   at Store.BusinessLogic.Services.UserService.GetUserById(Int32 userId) in C:\Users\Gennadii\Desktop\Anuitex\StoreApp\Store.BusinessLogic\Services\UserService.cs:line 24
   at Store.Presentation.Controllers.UserController.GetUserById(Int32 userId) in C:\Users\Gennadii\Desktop\Anuitex\StoreApp\Store.Presentation\Controllers\UserController.cs:line 29
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Store.Presentation.Middlewares.ErrorHandlerMiddleware.InvokeAsync(HttpContext context) in C:\Users\Gennadii\Desktop\Anuitex\StoreApp\Store.Presentation\Middlewares\ErrorHandlerMiddleware.cs:line 22
